package com.project.livechat.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette inspired by the intro screen
val md_theme_light_primary = Color(0xFFB2DFDB)
val md_theme_light_onPrimary = Color(0xFF1A2A2A)
val md_theme_light_primaryContainer = Color(0xFFDDF4F1)
val md_theme_light_onPrimaryContainer = Color(0xFF1A2A2A)
val md_theme_light_secondary = Color(0xFFCFE8E6)
val md_theme_light_onSecondary = Color(0xFF1A2A2A)
val md_theme_light_secondaryContainer = Color(0xFFE8F5F4)
val md_theme_light_onSecondaryContainer = Color(0xFF1A2A2A)
val md_theme_light_tertiary = Color(0xFF80CBC4)
val md_theme_light_onTertiary = Color(0xFF0F1F1D)
val md_theme_light_tertiaryContainer = Color(0xFF2A403F)
val md_theme_light_onTertiaryContainer = Color(0xFFD1E0DD)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF0FDFA)
val md_theme_light_onBackground = Color(0xFF3F5A57)
val md_theme_light_outline = Color(0xFF91ACA7)
val md_theme_light_inverseOnSurface = Color(0xFFE4F3F1)
val md_theme_light_inverseSurface = Color(0xFF3F5A57)
val md_theme_light_inversePrimary = Color(0xFF80CBC4)
val md_theme_light_surfaceTint = Color(0xFFB2DFDB)
val md_theme_light_outlineVariant = Color(0xFFD0E4E1)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF0FDFA)
val md_theme_light_onSurface = Color(0xFF3F5A57)
val md_theme_light_surfaceVariant = Color(0xFFE3F2F1)
val md_theme_light_onSurfaceVariant = Color(0xFF4F6A67)

// Dark palette aligned with intro screen dark gradient
val md_theme_dark_primary = Color(0xFF80CBC4)
val md_theme_dark_onPrimary = Color(0xFF0B1917)
val md_theme_dark_primaryContainer = Color(0xFF2A403F)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E0DD)
val md_theme_dark_secondary = Color(0xFF6A8D8A)
val md_theme_dark_onSecondary = Color(0xFFE0EEEC)
val md_theme_dark_secondaryContainer = Color(0xFF243534)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E0DD)
val md_theme_dark_tertiary = Color(0xFFB2DFDB)
val md_theme_dark_onTertiary = Color(0xFF0B1917)
val md_theme_dark_tertiaryContainer = Color(0xFF1F2E2D)
val md_theme_dark_onTertiaryContainer = Color(0xFFDDECE9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A2A2A)
val md_theme_dark_onBackground = Color(0xFFD1E0DD)
val md_theme_dark_outline = Color(0xFF4F6562)
val md_theme_dark_inverseOnSurface = Color(0xFF1A2A2A)
val md_theme_dark_inverseSurface = Color(0xFFE4F3F1)
val md_theme_dark_inversePrimary = Color(0xFFB2DFDB)
val md_theme_dark_surfaceTint = Color(0xFF80CBC4)
val md_theme_dark_outlineVariant = Color(0xFF2F4341)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF1A2A2A)
val md_theme_dark_onSurface = Color(0xFFD1E0DD)
val md_theme_dark_surfaceVariant = Color(0xFF2F4341)
val md_theme_dark_onSurfaceVariant = Color(0xFFB0C4C1)

val seed = Color(0xFFB2DFDB)
