@file:Suppress("ktlint:standard:no-wildcard-imports")

package com.edufelip.livechat.ui.resources

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import com.edufelip.livechat.resources.*
import com.edufelip.livechat.resources.Res
import org.jetbrains.compose.resources.stringResource

@Suppress("LongParameterList")
data class ContactsStrings(
    val loading: String = "Loading contacts…",
    val emptyState: String = "No contacts synced yet",
    val syncCta: String = "Sync Contacts",
    val syncing: String = "Syncing…",
    val syncingStateDescription: String = "Syncing contacts",
    val onLiveChatBadge: String = "On LiveChat",
    val inviteCta: String = "Invite",
    val inviteShareTitle: String = "Share LiveChat invite",
    val inviteShareUnavailable: String = "No apps available to share",
    val permissionDeniedMessage: String = "Enable contacts permission to sync your phonebook.",
    val screenTitle: String = "Contacts",
    val registeredSectionTitle: String = "On LiveChat",
    val inviteSectionTitle: String = "Invite to LiveChat",
    val validatingSectionMessage: String = "Validating contacts...",
    val searchPlaceholder: String = "Search name or number",
    val searchEmptyState: String = "No contacts match your search.",
)

data class SettingsStrings(
    val screenTitle: String = "Settings",
    val searchPlaceholder: String = "Search",
    val accountTitle: String = "Account",
    val accountDescription: String = "Profile, status, and linked phone number",
    val notificationsTitle: String = "Notifications",
    val notificationsDescription: String = "Mute, schedule quiet hours, sounds",
    val appearanceTitle: String = "Appearance",
    val appearanceDescription: String = "Themes, typography scale, accessibility",
    val privacyTitle: String = "Privacy",
    val privacyDescription: String = "Blocked contacts, invite preferences",
    val privacyPolicyTitle: String = "Privacy Policy",
    val privacyPolicyUrl: String = "https://www.portfolio.eduwaldo.com/livechat_privacy_policy.pdf",
    val footerAppNameIos: String = "LiveChat for iOS",
    val footerAppNameAndroid: String = "LiveChat for Android",
    val versionFormat: String = "Version %1\$s (%2\$s)",
    val openingSectionTemplate: String = "Opening %1\$s settings soon",
)

data class AccountStrings(
    val screenTitle: String = "Account Settings",
    val screenSubtitle: String = "Manage your profile details",
    val editCta: String = "Edit",
    val displayNameLabel: String = "Display Name",
    val displayNameMissing: String = "Add your name",
    val statusLabel: String = "Status Message",
    val phoneLabel: String = "Linked Phone Number",
    val emailLabel: String = "Email Address",
    val phoneReadOnlyHint: String = "Contact support to change",
    val phoneMissing: String = "No phone linked",
    val emailMissing: String = "Add an email",
    val statusPlaceholder: String = "Available for chat",
    val onlineLabel: String = "Online",
    val deleteTitle: String = "Delete Account",
    val deleteDescription: String = "Permanently remove your data",
    val deleteConfirmTitle: String = "Delete account?",
    val deleteConfirmBody: String = "This will permanently remove your data. This action can't be undone.",
    val deleteConfirmCta: String = "Delete",
    val editDisplayNameTitle: String = "Edit display name",
    val editDisplayNameDescription: String = "This is how your name appears to contacts.",
    val editStatusTitle: String = "Edit status message",
    val editStatusDescription: String = "Share a short status with your contacts.",
    val editEmailTitle: String = "Edit email address",
    val editEmailDescription: String = "Use an email for account recovery.",
    val editEmailSendCta: String = "Send verification",
    val editEmailVerifyTitle: String = "Check your email",
    val editEmailVerifyDescription: String = "We sent a verification link to %1\$s. Open it to confirm.",
    val editEmailVerifyCta: String = "I've verified",
    val editEmailChangeCta: String = "Change email",
    val editEmailResendCta: String = "Resend email",
    val saveCta: String = "Save",
    val deleteFarewellTitle: String = "We're sorry to see you go",
    val deleteFarewellBody: String = "Ok, hope we see you back soon.",
    val deleteCountdownCta: String = "Delete in %1\$ds",
    val deleteCountdownReadyCta: String = "Delete account",
    val deleteReauthTitle: String = "Confirm it's you",
    val deleteReauthBody: String = "Enter the code sent to %1\$s to continue.",
    val deleteReauthCodeLabel: String = "Verification code",
    val deleteReauthCodePlaceholder: String = "6-digit code",
    val deleteReauthCta: String = "Verify and delete",
    val deleteReauthResend: String = "Resend code",
)

data class NotificationsStrings(
    val screenTitle: String = "Notifications",
    val generalSection: String = "General",
    val quietHoursSection: String = "Quiet Hours",
    val advancedSection: String = "Advanced",
    val pushTitle: String = "Push Notifications",
    val pushSubtitle: String = "Receive messages when away",
    val permissionDisabledHint: String = "Notifications disabled in system settings.",
    val soundTitle: String = "Sound",
    val soundSheetTitle: String = "Notification sound",
    val soundSheetDescription: String = "Choose a tone for incoming messages.",
    val soundOptionPopcorn: String = "Popcorn",
    val soundOptionChime: String = "Chime",
    val soundOptionRipple: String = "Ripple",
    val soundOptionSilent: String = "Silent",
    val quietHoursTitle: String = "Scheduled Quiet Mode",
    val quietHoursSubtitle: String = "Mute notifications during set times",
    val quietHoursFromLabel: String = "From",
    val quietHoursToLabel: String = "To",
    val quietHoursFromPlaceholder: String = "22:00",
    val quietHoursToPlaceholder: String = "07:00",
    val quietHoursSheetTitle: String = "Edit quiet hours",
    val quietHoursSheetDescription: String = "Use 24h format (HH:MM).",
    val vibrationTitle: String = "In-App Vibration",
    val previewTitle: String = "Show Message Preview",
    val previewSubtitle: String = "Display text in banners",
    val resetTitle: String = "Reset Notifications",
    val saveCta: String = "Save",
)

data class AppearanceStrings(
    val screenTitle: String = "Appearance",
    val themesSection: String = "Themes",
    val typographySection: String = "Typography scale",
    val accessibilitySection: String = "Accessibility",
    val themeSystemTitle: String = "System default",
    val themeSystemSubtitle: String = "Match your device settings",
    val themeLightTitle: String = "Light mode",
    val themeLightSubtitle: String = "Always bright and clear",
    val themeDarkTitle: String = "Dark mode",
    val themeDarkSubtitle: String = "Easy on the eyes",
    val typographySmallLabel: String = "Small",
    val typographyDefaultLabel: String = "Default",
    val typographyLargeLabel: String = "Large",
    val typographySample: String =
        "The quick brown fox jumps over the lazy dog. " +
            "Adjust the slider to see how text will appear in your chats.",
    val reduceMotionTitle: String = "Reduce motion",
    val reduceMotionSubtitle: String = "Minimize animations",
    val highContrastTitle: String = "High contrast",
    val highContrastSubtitle: String = "Increase text legibility",
    val resetTitle: String = "Reset appearance",
)

data class PrivacyStrings(
    val screenTitle: String = "Privacy",
    val screenSubtitle: String = "Manage your visibility and data",
    val blockedContactsTitle: String = "Blocked Contacts",
    val blockedContactsSubtitle: String =
        "View and manage people you've blocked",
    val blockedContactsEmpty: String = "No blocked contacts yet",
    val blockedContactUnknown: String = "Unknown user",
    val unblockCta: String = "Unblock",
    val invitePreferencesTitle: String = "Invite Preferences",
    val invitePreferencesSubtitle: String =
        "Control who can add you to groups and channels",
    val inviteEveryone: String = "Everyone",
    val inviteContacts: String = "My Contacts",
    val inviteNobody: String = "Nobody",
    val lastSeenTitle: String = "Last Seen & Online",
    val lastSeenSheetDescription: String = "Choose who can see your last seen status.",
    val lastSeenEveryone: String = "Everyone",
    val lastSeenContacts: String = "My Contacts",
    val lastSeenNobody: String = "Nobody",
    val readReceiptsTitle: String = "Read Receipts",
    val readReceiptsSubtitle: String =
        "If turned off, you won't see read receipts from other people either.",
    val shareUsageDataTitle: String = "Share Usage Data",
    val shareUsageDataSubtitle: String =
        "Help us improve LiveChat by automatically sending diagnostic data.",
    val privacyPolicyTitle: String = "Privacy Policy",
    val privacyPolicySubtitle: String =
        "View our privacy policy and terms of service.",
    val saveCta: String = "Save",
)

data class HomeStrings(
    val conversationTitle: String = "Conversation",
    val chatsTab: String = "Chats",
    val callsTab: String = "Calls",
    val settingsTab: String = "Settings",
    val backCta: String = "Back",
)

data class OnboardingStrings(
    val welcomeTitle: String = "Connect instantly with friends.",
    val welcomeSubtitle: String =
        "The simplest way to text, call, and share moments with the people who matter most.",
    val welcomeCta: String = "Start Messaging",
    val welcomeHelpCta: String = "Help",
    val welcomeHelpUrl: String = "https://www.portfolio.eduwaldo.com",
    val welcomeTermsMessage: String =
        "By continuing, you agree to our Terms of Service and Privacy Policy.",
    val welcomeTermsUrl: String =
        "https://www.portfolio.eduwaldo.com/livechat_terms_of_service.pdf",
    val welcomePrivacyUrl: String =
        "https://www.portfolio.eduwaldo.com/livechat_privacy_policy.pdf",
    val welcomeBrandName: String = "LiveChat",
    val phoneTitle: String = "Enter your phone number",
    val phoneSubtitle: String = "We'll send a verification code to confirm it's you.",
    val phoneFieldLabel: String = "Phone number",
    val phoneFieldPlaceholder: String = "Digits only",
    val phoneCountryLabel: String = "Country",
    val phoneTermsMessage: String =
        "By tapping \"Continue\", you agree to our Terms of Service and Privacy Policy.",
    val continueCta: String = "Continue",
    val defaultPhoneSample: String = "5550100",
    val invalidPhoneError: String = "Please enter a valid phone number",
    val startVerificationError: String = "Unable to start verification",
    val otpTitle: String = "Enter the 6-digit code",
    val otpSubtitle: String = "We just sent a verification code to your number.",
    val otpFieldLabel: String = "Code",
    val resendCta: String = "Resend code",
    val resendCountdownLabel: @Composable (Int) -> String = { seconds ->
        "Resend available in ${seconds.coerceAtLeast(0)}s"
    },
    val verifyCta: String = "Verify",
    val successTitle: String = "You're all set!",
    val successSubtitle: String = "Your account is ready. Start chatting with your contacts now.",
    val successCta: String = "Start chatting",
    val successChecklistSyncTitle: String = "Sync Contacts",
    val successChecklistSyncSubtitle: String = "Find friends who are already here.",
    val successChecklistNotifyTitle: String = "Enable Notifications",
    val successChecklistNotifySubtitle: String = "Don't miss a message.",
    val countryPickerTitle: String = "Select your country",
    val countryPickerSearchPlaceholder: String = "Search by country or code",
    val countryPickerEmpty: String = "No countries found",
    val countryPickerClose: String = "Close",
    val defaultCountryIso: String = "US",
    val priorityCountryIsos: List<String> = listOf("US", "CA", "BR"),
    val invalidVerificationCode: String = "Invalid verification code",
    val tooManyRequests: String = "Too many attempts. Try again later.",
    val quotaExceeded: String = "SMS quota exceeded. Please try again later.",
    val codeExpired: String = "The code has expired. Request a new one.",
    val networkError: String = "Network error. Check your connection.",
    val resendNotAvailable: String = "You can request a new code shortly.",
    val configurationError: String = "Phone authentication is not configured.",
    val unknownError: String = "Unexpected error. Try again.",
)

data class ConversationStrings(
    val archivedLabel: String = "Archived conversation",
    val mutedLabel: String = "Muted conversation",
    val mutedUntilPrefix: String = "Muted until",
    val loadingMessages: String = "Loading messages…",
    val searchPlaceholder: String = "Search conversations",
    val loadingList: String = "Loading conversations…",
    val emptyList: String = "No conversations yet",
    val emptyListSubtitle: String = "Tap the compose button to start chatting with your contacts.",
    val emptyListCta: String = "Find Contacts",
    val pinnedSectionTitle: String = "Pinned",
    val othersSectionTitle: String = "Others",
    val composeAction: String = "New chat",
    val youPrefix: String = "You:",
    val filterAll: String = "All",
    val filterUnread: String = "Unread",
    val filterPinned: String = "Pinned",
    val filterArchived: String = "Archived",
    val audioMessageLabel: String = "Audio message",
    val audioShortLabel: String = "Audio",
    val pinAction: String = "Pin",
    val unpinAction: String = "Unpin",
    val muteAction: String = "Mute",
    val unmuteAction: String = "Unmute",
    val archiveAction: String = "Archive",
    val unarchiveAction: String = "Unarchive",
    val permissionTitle: String = "Permission needed",
    val microphonePermissionHint: String = "Microphone permission is required to record audio.",
    val microphonePermissionDialog: String = "Microphone permission is blocked. Please enable it in Settings.",
    val photoPermissionHint: String = "Allow photo/gallery access to attach images.",
    val photoPermissionDialog: String = "Photo permissions are blocked. Please enable them in Settings.",
    val cameraPermissionHint: String = "Camera permission is required to take a photo.",
    val cameraPermissionDialog: String = "Camera permission is blocked. Please enable it in Settings.",
    val recordingStartError: String = "Unable to start recording.",
    val imageAttachError: String = "Unable to attach image.",
    val photoCaptureError: String = "Unable to capture photo.",
    val recordingCancelDescription: String = "Cancel recording",
    val recordingSendDescription: String = "Send recording",
    val recordingLabel: @Composable (String) -> String = { duration -> "Recording $duration" },
    val playAudioDescription: String = "Play audio",
    val stopAudioDescription: String = "Stop audio",
    val playingAudioLabel: String = "Playing audio",
    val imageMessageDescription: String = "Image message",
    val imageLabel: String = "Image",
    val imageFallbackLabel: @Composable (String) -> String = { name -> "Image: $name" },
    val messagePlaceholder: String = "Message…",
    val messageFailed: String = "Message failed",
    val copyAction: String = "Copy",
    val deleteAction: String = "Delete",
    val messageCopied: String = "Copied to clipboard",
    val retryMessageTitle: String = "Message failed",
    val retryMessageBody: String = "Couldn't send this message. Retry?",
    val retryMessageCta: String = "Retry",
    val sendMessage: String = "Send message",
    val pickImage: String = "Pick image",
    val takePhoto: String = "Take photo",
    val recordAudio: String = "Record audio",
    val stopRecording: String = "Stop recording",
    val sendRecording: String = "Send recording",
)

data class GeneralStrings(
    val ok: String = "OK",
    val cancel: String = "Cancel",
    val openSettings: String = "Open Settings",
    val dismiss: String = "Dismiss",
    val errorTitle: String = "Something went wrong",
    val comingSoon: String = "Coming soon",
    val timePeriodAm: String = "AM",
    val timePeriodPm: String = "PM",
    val homeDestinationTransitionLabel: String = "homeDestinationTransition",
)

data class PreviewStrings(
    val contactPrimaryName: String = "Ava Harper",
    val contactSecondaryName: String = "Brandon Diaz",
    val contactTertiaryName: String = "Chioma Ade",
    val contactPrimaryPhone: String = "+1 555 0100",
    val contactSecondaryPhone: String = "+1 555 0101",
    val contactTertiaryPhone: String = "+1 555 0102",
    val messageOutgoing: String =
        "Hey there! This is a preview message to show how your own messages appear in bubbles.",
    val messageIncoming: String = "Hi there! Compose Multiplatform previews are working like a charm!",
    val messageSnippetSecondary: String = "Let's schedule a quick catch-up later today.",
)

data class LiveChatStrings(
    val contacts: ContactsStrings = ContactsStrings(),
    val settings: SettingsStrings = SettingsStrings(),
    val account: AccountStrings = AccountStrings(),
    val notifications: NotificationsStrings = NotificationsStrings(),
    val appearance: AppearanceStrings = AppearanceStrings(),
    val privacy: PrivacyStrings = PrivacyStrings(),
    val home: HomeStrings = HomeStrings(),
    val onboarding: OnboardingStrings = OnboardingStrings(),
    val conversation: ConversationStrings = ConversationStrings(),
    val general: GeneralStrings = GeneralStrings(),
    val preview: PreviewStrings = PreviewStrings(),
)

val LocalLiveChatStrings = staticCompositionLocalOf { LiveChatStrings() }

@Composable
fun liveChatStrings(): LiveChatStrings = LocalLiveChatStrings.current

@Composable
fun rememberLiveChatStrings(): LiveChatStrings {
    val contacts =
        ContactsStrings(
            loading = stringResource(Res.string.contacts_loading),
            emptyState = stringResource(Res.string.contacts_empty_state),
            syncCta = stringResource(Res.string.contacts_sync_cta),
            syncing = stringResource(Res.string.contacts_syncing),
            syncingStateDescription = stringResource(Res.string.contacts_syncing_state_description),
            onLiveChatBadge = stringResource(Res.string.contacts_on_livechat_badge),
            inviteCta = stringResource(Res.string.contacts_invite_cta),
            inviteShareTitle = stringResource(Res.string.contacts_invite_share_title),
            inviteShareUnavailable = stringResource(Res.string.contacts_invite_share_unavailable),
            permissionDeniedMessage = stringResource(Res.string.contacts_permission_denied_message),
            screenTitle = stringResource(Res.string.contacts_screen_title),
            registeredSectionTitle = stringResource(Res.string.contacts_registered_section_title),
            inviteSectionTitle = stringResource(Res.string.contacts_invite_section_title),
            validatingSectionMessage = stringResource(Res.string.contacts_validating_section_label),
            searchPlaceholder = stringResource(Res.string.contacts_search_placeholder),
            searchEmptyState = stringResource(Res.string.contacts_search_empty_state),
        )

    val settings =
        SettingsStrings(
            screenTitle = stringResource(Res.string.settings_screen_title),
            searchPlaceholder = stringResource(Res.string.settings_search_placeholder),
            accountTitle = stringResource(Res.string.settings_account_title),
            accountDescription = stringResource(Res.string.settings_account_description),
            notificationsTitle = stringResource(Res.string.settings_notifications_title),
            notificationsDescription = stringResource(Res.string.settings_notifications_description),
            appearanceTitle = stringResource(Res.string.settings_appearance_title),
            appearanceDescription = stringResource(Res.string.settings_appearance_description),
            privacyTitle = stringResource(Res.string.settings_privacy_title),
            privacyDescription = stringResource(Res.string.settings_privacy_description),
            privacyPolicyTitle = stringResource(Res.string.settings_privacy_policy_title),
            privacyPolicyUrl = stringResource(Res.string.settings_privacy_policy_url),
            footerAppNameIos = stringResource(Res.string.settings_footer_app_name_ios),
            footerAppNameAndroid = stringResource(Res.string.settings_footer_app_name_android),
            versionFormat = stringResource(Res.string.settings_version_format),
            openingSectionTemplate = stringResource(Res.string.settings_opening_section_toast),
        )

    val account =
        AccountStrings(
            screenTitle = stringResource(Res.string.account_screen_title),
            screenSubtitle = stringResource(Res.string.account_screen_subtitle),
            editCta = stringResource(Res.string.account_edit_cta),
            displayNameLabel = stringResource(Res.string.account_display_name_label),
            displayNameMissing = stringResource(Res.string.account_display_name_missing),
            statusLabel = stringResource(Res.string.account_status_label),
            phoneLabel = stringResource(Res.string.account_phone_label),
            emailLabel = stringResource(Res.string.account_email_label),
            phoneReadOnlyHint = stringResource(Res.string.account_phone_readonly_hint),
            phoneMissing = stringResource(Res.string.account_phone_missing),
            emailMissing = stringResource(Res.string.account_email_missing),
            statusPlaceholder = stringResource(Res.string.account_status_placeholder),
            onlineLabel = stringResource(Res.string.account_online_label),
            deleteTitle = stringResource(Res.string.account_delete_title),
            deleteDescription = stringResource(Res.string.account_delete_description),
            deleteConfirmTitle = stringResource(Res.string.account_delete_confirm_title),
            deleteConfirmBody = stringResource(Res.string.account_delete_confirm_body),
            deleteConfirmCta = stringResource(Res.string.account_delete_confirm_cta),
            editDisplayNameTitle = stringResource(Res.string.account_edit_display_name_title),
            editDisplayNameDescription = stringResource(Res.string.account_edit_display_name_description),
            editStatusTitle = stringResource(Res.string.account_edit_status_title),
            editStatusDescription = stringResource(Res.string.account_edit_status_description),
            editEmailTitle = stringResource(Res.string.account_edit_email_title),
            editEmailDescription = stringResource(Res.string.account_edit_email_description),
            editEmailSendCta = stringResource(Res.string.account_edit_email_send_cta),
            editEmailVerifyTitle = stringResource(Res.string.account_edit_email_verify_title),
            editEmailVerifyDescription = stringResource(Res.string.account_edit_email_verify_description),
            editEmailVerifyCta = stringResource(Res.string.account_edit_email_verify_cta),
            editEmailChangeCta = stringResource(Res.string.account_edit_email_change_cta),
            editEmailResendCta = stringResource(Res.string.account_edit_email_resend_cta),
            saveCta = stringResource(Res.string.account_save_cta),
            deleteFarewellTitle = stringResource(Res.string.account_delete_farewell_title),
            deleteFarewellBody = stringResource(Res.string.account_delete_farewell_body),
            deleteCountdownCta = stringResource(Res.string.account_delete_countdown_cta),
            deleteCountdownReadyCta = stringResource(Res.string.account_delete_countdown_ready_cta),
            deleteReauthTitle = stringResource(Res.string.account_delete_reauth_title),
            deleteReauthBody = stringResource(Res.string.account_delete_reauth_body),
            deleteReauthCodeLabel = stringResource(Res.string.account_delete_reauth_code_label),
            deleteReauthCodePlaceholder = stringResource(Res.string.account_delete_reauth_code_placeholder),
            deleteReauthCta = stringResource(Res.string.account_delete_reauth_cta),
            deleteReauthResend = stringResource(Res.string.account_delete_reauth_resend),
        )

    val notifications =
        NotificationsStrings(
            screenTitle = stringResource(Res.string.notifications_screen_title),
            generalSection = stringResource(Res.string.notifications_general_section),
            quietHoursSection = stringResource(Res.string.notifications_quiet_hours_section),
            advancedSection = stringResource(Res.string.notifications_advanced_section),
            pushTitle = stringResource(Res.string.notifications_push_title),
            pushSubtitle = stringResource(Res.string.notifications_push_subtitle),
            permissionDisabledHint = stringResource(Res.string.notifications_permission_disabled_hint),
            soundTitle = stringResource(Res.string.notifications_sound_title),
            soundSheetTitle = stringResource(Res.string.notifications_sound_sheet_title),
            soundSheetDescription = stringResource(Res.string.notifications_sound_sheet_description),
            soundOptionPopcorn = stringResource(Res.string.notifications_sound_option_popcorn),
            soundOptionChime = stringResource(Res.string.notifications_sound_option_chime),
            soundOptionRipple = stringResource(Res.string.notifications_sound_option_ripple),
            soundOptionSilent = stringResource(Res.string.notifications_sound_option_silent),
            quietHoursTitle = stringResource(Res.string.notifications_quiet_hours_title),
            quietHoursSubtitle = stringResource(Res.string.notifications_quiet_hours_subtitle),
            quietHoursFromLabel = stringResource(Res.string.notifications_quiet_hours_from_label),
            quietHoursToLabel = stringResource(Res.string.notifications_quiet_hours_to_label),
            quietHoursFromPlaceholder = stringResource(Res.string.notifications_quiet_hours_from_placeholder),
            quietHoursToPlaceholder = stringResource(Res.string.notifications_quiet_hours_to_placeholder),
            quietHoursSheetTitle = stringResource(Res.string.notifications_quiet_hours_sheet_title),
            quietHoursSheetDescription = stringResource(Res.string.notifications_quiet_hours_sheet_description),
            vibrationTitle = stringResource(Res.string.notifications_vibration_title),
            previewTitle = stringResource(Res.string.notifications_preview_title),
            previewSubtitle = stringResource(Res.string.notifications_preview_subtitle),
            resetTitle = stringResource(Res.string.notifications_reset_title),
            saveCta = stringResource(Res.string.notifications_save_cta),
        )

    val appearance =
        AppearanceStrings(
            screenTitle = stringResource(Res.string.appearance_screen_title),
            themesSection = stringResource(Res.string.appearance_themes_section),
            typographySection = stringResource(Res.string.appearance_typography_section),
            accessibilitySection = stringResource(Res.string.appearance_accessibility_section),
            themeSystemTitle = stringResource(Res.string.appearance_theme_system_title),
            themeSystemSubtitle = stringResource(Res.string.appearance_theme_system_subtitle),
            themeLightTitle = stringResource(Res.string.appearance_theme_light_title),
            themeLightSubtitle = stringResource(Res.string.appearance_theme_light_subtitle),
            themeDarkTitle = stringResource(Res.string.appearance_theme_dark_title),
            themeDarkSubtitle = stringResource(Res.string.appearance_theme_dark_subtitle),
            typographySmallLabel = stringResource(Res.string.appearance_typography_small_label),
            typographyDefaultLabel = stringResource(Res.string.appearance_typography_default_label),
            typographyLargeLabel = stringResource(Res.string.appearance_typography_large_label),
            typographySample = stringResource(Res.string.appearance_typography_sample),
            reduceMotionTitle = stringResource(Res.string.appearance_reduce_motion_title),
            reduceMotionSubtitle = stringResource(Res.string.appearance_reduce_motion_subtitle),
            highContrastTitle = stringResource(Res.string.appearance_high_contrast_title),
            highContrastSubtitle = stringResource(Res.string.appearance_high_contrast_subtitle),
            resetTitle = stringResource(Res.string.appearance_reset_title),
        )

    val privacy =
        PrivacyStrings(
            screenTitle = stringResource(Res.string.privacy_screen_title),
            screenSubtitle = stringResource(Res.string.privacy_screen_subtitle),
            blockedContactsTitle = stringResource(Res.string.privacy_blocked_contacts_title),
            blockedContactsSubtitle = stringResource(Res.string.privacy_blocked_contacts_subtitle),
            blockedContactsEmpty = stringResource(Res.string.privacy_blocked_contacts_empty),
            blockedContactUnknown = stringResource(Res.string.privacy_blocked_contact_unknown),
            unblockCta = stringResource(Res.string.privacy_unblock_cta),
            invitePreferencesTitle = stringResource(Res.string.privacy_invite_preferences_title),
            invitePreferencesSubtitle = stringResource(Res.string.privacy_invite_preferences_subtitle),
            inviteEveryone = stringResource(Res.string.privacy_invite_everyone),
            inviteContacts = stringResource(Res.string.privacy_invite_contacts),
            inviteNobody = stringResource(Res.string.privacy_invite_nobody),
            lastSeenTitle = stringResource(Res.string.privacy_last_seen_title),
            lastSeenSheetDescription = stringResource(Res.string.privacy_last_seen_sheet_description),
            lastSeenEveryone = stringResource(Res.string.privacy_last_seen_everyone),
            lastSeenContacts = stringResource(Res.string.privacy_last_seen_contacts),
            lastSeenNobody = stringResource(Res.string.privacy_last_seen_nobody),
            readReceiptsTitle = stringResource(Res.string.privacy_read_receipts_title),
            readReceiptsSubtitle = stringResource(Res.string.privacy_read_receipts_subtitle),
            shareUsageDataTitle = stringResource(Res.string.privacy_share_usage_data_title),
            shareUsageDataSubtitle = stringResource(Res.string.privacy_share_usage_data_subtitle),
            privacyPolicyTitle = stringResource(Res.string.privacy_policy_title),
            privacyPolicySubtitle = stringResource(Res.string.privacy_policy_subtitle),
            saveCta = stringResource(Res.string.privacy_save_cta),
        )

    val home =
        HomeStrings(
            conversationTitle = stringResource(Res.string.home_conversation_title),
            chatsTab = stringResource(Res.string.home_chats_tab),
            callsTab = stringResource(Res.string.home_calls_tab),
            settingsTab = stringResource(Res.string.home_settings_tab),
            backCta = stringResource(Res.string.home_back_cta),
        )

    val conversation =
        ConversationStrings(
            archivedLabel = stringResource(Res.string.conversation_archived_label),
            mutedLabel = stringResource(Res.string.conversation_muted_label),
            mutedUntilPrefix = stringResource(Res.string.conversation_muted_until_prefix),
            loadingMessages = stringResource(Res.string.conversation_loading_messages),
            searchPlaceholder = stringResource(Res.string.conversation_search_placeholder),
            loadingList = stringResource(Res.string.conversation_loading_list),
            emptyList = stringResource(Res.string.conversation_empty_list),
            emptyListSubtitle = stringResource(Res.string.conversation_empty_list_subtitle),
            emptyListCta = stringResource(Res.string.conversation_empty_list_cta),
            pinnedSectionTitle = stringResource(Res.string.conversation_section_pinned),
            othersSectionTitle = stringResource(Res.string.conversation_section_others),
            composeAction = stringResource(Res.string.conversation_compose_action),
            youPrefix = stringResource(Res.string.conversation_you_prefix),
            filterAll = stringResource(Res.string.conversation_filter_all),
            filterUnread = stringResource(Res.string.conversation_filter_unread),
            filterPinned = stringResource(Res.string.conversation_filter_pinned),
            filterArchived = stringResource(Res.string.conversation_filter_archived),
            audioMessageLabel = stringResource(Res.string.conversation_audio_message_label),
            audioShortLabel = stringResource(Res.string.conversation_audio_short_label),
            pinAction = stringResource(Res.string.conversation_pin_action),
            unpinAction = stringResource(Res.string.conversation_unpin_action),
            muteAction = stringResource(Res.string.conversation_mute_action),
            unmuteAction = stringResource(Res.string.conversation_unmute_action),
            archiveAction = stringResource(Res.string.conversation_archive_action),
            unarchiveAction = stringResource(Res.string.conversation_unarchive_action),
            permissionTitle = stringResource(Res.string.conversation_permission_title),
            microphonePermissionHint = stringResource(Res.string.conversation_microphone_permission_hint),
            microphonePermissionDialog = stringResource(Res.string.conversation_microphone_permission_dialog),
            photoPermissionHint = stringResource(Res.string.conversation_photo_permission_hint),
            photoPermissionDialog = stringResource(Res.string.conversation_photo_permission_dialog),
            cameraPermissionHint = stringResource(Res.string.conversation_camera_permission_hint),
            cameraPermissionDialog = stringResource(Res.string.conversation_camera_permission_dialog),
            recordingStartError = stringResource(Res.string.conversation_recording_start_error),
            imageAttachError = stringResource(Res.string.conversation_image_attach_error),
            photoCaptureError = stringResource(Res.string.conversation_photo_capture_error),
            recordingCancelDescription = stringResource(Res.string.conversation_recording_cancel_description),
            recordingSendDescription = stringResource(Res.string.conversation_recording_send_description),
            recordingLabel = { duration ->
                stringResource(
                    Res.string.conversation_recording_label,
                    duration,
                )
            },
            playAudioDescription = stringResource(Res.string.conversation_play_audio_description),
            stopAudioDescription = stringResource(Res.string.conversation_stop_audio_description),
            playingAudioLabel = stringResource(Res.string.conversation_playing_audio_label),
            imageMessageDescription = stringResource(Res.string.conversation_image_message_description),
            imageLabel = stringResource(Res.string.conversation_image_label),
            imageFallbackLabel = { name ->
                stringResource(
                    Res.string.conversation_image_fallback_template,
                    name,
                )
            },
            messagePlaceholder = stringResource(Res.string.conversation_message_placeholder),
            messageFailed = stringResource(Res.string.conversation_message_failed),
            copyAction = stringResource(Res.string.conversation_message_copy_action),
            deleteAction = stringResource(Res.string.conversation_message_delete_action),
            messageCopied = stringResource(Res.string.conversation_message_copied),
            retryMessageTitle = stringResource(Res.string.conversation_message_retry_title),
            retryMessageBody = stringResource(Res.string.conversation_message_retry_body),
            retryMessageCta = stringResource(Res.string.conversation_message_retry_cta),
            sendMessage = stringResource(Res.string.conversation_send_message),
            pickImage = stringResource(Res.string.conversation_pick_image),
            takePhoto = stringResource(Res.string.conversation_take_photo),
            recordAudio = stringResource(Res.string.conversation_record_audio),
            stopRecording = stringResource(Res.string.conversation_stop_recording),
            sendRecording = stringResource(Res.string.conversation_send_recording),
        )

    val onboardingPriorityIsos =
        stringResource(Res.string.onboarding_priority_country_isos)
            .split(',')
            .mapNotNull { code -> code.trim().takeIf { it.isNotEmpty() } }
    val onboardingDefaultIso =
        stringResource(Res.string.onboarding_default_country_iso)
            .trim()
            .ifEmpty { onboardingPriorityIsos.firstOrNull().orEmpty() }

    val onboarding =
        OnboardingStrings(
            welcomeTitle = stringResource(Res.string.welcome_title),
            welcomeSubtitle = stringResource(Res.string.welcome_subtitle),
            welcomeCta = stringResource(Res.string.welcome_cta),
            welcomeHelpCta = stringResource(Res.string.welcome_help_cta),
            welcomeHelpUrl = stringResource(Res.string.welcome_help_url),
            welcomeTermsMessage = stringResource(Res.string.welcome_terms_message),
            welcomeTermsUrl = stringResource(Res.string.welcome_terms_url),
            welcomePrivacyUrl = stringResource(Res.string.welcome_privacy_url),
            welcomeBrandName = stringResource(Res.string.welcome_brand_name),
            phoneTitle = stringResource(Res.string.onboarding_phone_title),
            phoneSubtitle = stringResource(Res.string.onboarding_phone_subtitle),
            phoneFieldLabel = stringResource(Res.string.onboarding_phone_field_label),
            phoneFieldPlaceholder = stringResource(Res.string.onboarding_phone_field_placeholder),
            phoneCountryLabel = stringResource(Res.string.onboarding_phone_country_label),
            phoneTermsMessage = stringResource(Res.string.onboarding_phone_terms_message),
            continueCta = stringResource(Res.string.onboarding_continue_cta),
            defaultPhoneSample = stringResource(Res.string.onboarding_default_phone_sample),
            invalidPhoneError = stringResource(Res.string.onboarding_invalid_phone_error),
            startVerificationError = stringResource(Res.string.onboarding_start_verification_error),
            otpTitle = stringResource(Res.string.onboarding_otp_title),
            otpSubtitle = stringResource(Res.string.onboarding_otp_subtitle),
            otpFieldLabel = stringResource(Res.string.onboarding_otp_field_label),
            resendCta = stringResource(Res.string.onboarding_resend_cta),
            resendCountdownLabel = { seconds ->
                stringResource(
                    Res.string.onboarding_resend_countdown_label,
                    seconds.coerceAtLeast(0),
                )
            },
            verifyCta = stringResource(Res.string.onboarding_verify_cta),
            successTitle = stringResource(Res.string.onboarding_success_title),
            successSubtitle = stringResource(Res.string.onboarding_success_subtitle),
            successCta = stringResource(Res.string.onboarding_success_cta),
            successChecklistSyncTitle = stringResource(Res.string.onboarding_success_checklist_sync_title),
            successChecklistSyncSubtitle = stringResource(Res.string.onboarding_success_checklist_sync_subtitle),
            successChecklistNotifyTitle = stringResource(Res.string.onboarding_success_checklist_notify_title),
            successChecklistNotifySubtitle = stringResource(Res.string.onboarding_success_checklist_notify_subtitle),
            countryPickerTitle = stringResource(Res.string.onboarding_country_picker_title),
            countryPickerSearchPlaceholder = stringResource(Res.string.onboarding_country_picker_search_placeholder),
            countryPickerEmpty = stringResource(Res.string.onboarding_country_picker_empty),
            countryPickerClose = stringResource(Res.string.onboarding_country_picker_close),
            defaultCountryIso = onboardingDefaultIso,
            priorityCountryIsos = onboardingPriorityIsos,
            invalidVerificationCode = stringResource(Res.string.onboarding_invalid_verification_code),
            tooManyRequests = stringResource(Res.string.onboarding_too_many_requests),
            quotaExceeded = stringResource(Res.string.onboarding_quota_exceeded),
            codeExpired = stringResource(Res.string.onboarding_code_expired),
            networkError = stringResource(Res.string.onboarding_network_error),
            resendNotAvailable = stringResource(Res.string.onboarding_resend_not_available),
            configurationError = stringResource(Res.string.onboarding_configuration_error),
            unknownError = stringResource(Res.string.onboarding_unknown_error),
        )

    val general =
        GeneralStrings(
            ok = stringResource(Res.string.general_ok),
            cancel = stringResource(Res.string.general_cancel),
            openSettings = stringResource(Res.string.general_open_settings),
            dismiss = stringResource(Res.string.general_dismiss),
            errorTitle = stringResource(Res.string.general_error_title),
            comingSoon = stringResource(Res.string.general_coming_soon),
            timePeriodAm = stringResource(Res.string.general_time_period_am),
            timePeriodPm = stringResource(Res.string.general_time_period_pm),
            homeDestinationTransitionLabel = stringResource(Res.string.general_home_destination_transition_label),
        )

    val preview =
        PreviewStrings(
            contactPrimaryName = stringResource(Res.string.preview_contact_primary_name),
            contactSecondaryName = stringResource(Res.string.preview_contact_secondary_name),
            contactTertiaryName = stringResource(Res.string.preview_contact_tertiary_name),
            contactPrimaryPhone = stringResource(Res.string.preview_contact_primary_phone),
            contactSecondaryPhone = stringResource(Res.string.preview_contact_secondary_phone),
            contactTertiaryPhone = stringResource(Res.string.preview_contact_tertiary_phone),
            messageOutgoing = stringResource(Res.string.preview_message_outgoing),
            messageIncoming = stringResource(Res.string.preview_message_incoming),
            messageSnippetSecondary = stringResource(Res.string.preview_message_snippet_secondary),
        )

    return LiveChatStrings(
        contacts = contacts,
        settings = settings,
        account = account,
        notifications = notifications,
        appearance = appearance,
        privacy = privacy,
        home = home,
        conversation = conversation,
        onboarding = onboarding,
        general = general,
        preview = preview,
    )
}
